### ISSUE TITLE
How do I make a podspec file for svn repo?

### ISSUE THREAD

**Issue by dehengxu** [dustywusty/cocoapods-repo-svn#2]
As title.

**Comment by xiaozi4624** [comment]
How to do with this  s.dependency?

**Comment by malaiseven** [comment]
Hi,

How to add dependency SVN project path in my Podspec.

Ex: Project1 (SVN)
          -Project2 (SVN)
             -Project3 (SVN)

When i Pod "URL to Project 2", It creates pod for Project2 not created for Porject3. But Project2 is dependent on Project3. 

How to specify the SVN path for Project3 in Project2 podspec. Thanks in advance.

Project2.podspec  Looks like:

Pod::Spec.new do |s|
s.name         = ‘Project2’
s.version      = '0.0.1'
s.summary      = ''
s.homepage     = ‘svn url’
s.authors      = ‘authr’
s.source       = { :svn => ‘SVN url to Project2’ }
s.source_files = '**/*.{h,m}'

pch_AF = <<-EOS
#ifndef TARGET_OS_IOS
#define TARGET_OS_IOS TARGET_OS_IPHONE
#endif
#ifndef TARGET_OS_WATCH
#define TARGET_OS_WATCH 0
#endif
#ifndef TARGET_OS_TV
#define TARGET_OS_TV 0
#endif
EOS
s.prefix_header_contents = pch_AF
s.ios.deployment_target = '7.0'
s.osx.deployment_target = '10.9'
s.watchos.deployment_target = '2.0'
s.tvos.deployment_target = '9.0'

s.dependency 'Project3', :svn => ‘url_of_podspec.podspec'

s.dependency 'AFNetworking'
s.dependency 'Mantle'
s.dependency 'XMLDictionary'
end
